# Generated by Django 4.2.2 on 2023-08-23 15:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="phone_number",
            field=models.CharField(default="", max_length=15, unique=True),
        ),
    ]
